name: HarmTip
favicon: null
layout_spectrum: 0.5938837402500212
typography_spectrum: 0.9477153646294028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6362423438113183
  lightness: 0.1035945217590779
  saturation: 0.11254176637157798
  rhythmicContrast: 0.3548107501119375
purpose: []
